version: '3.3'
name: ekb-api-1
services:
  db:
    image: postgres:15-alpine
    container_name: a-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Colombo
      - PGTZ=Asia/Colombo
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - net

  cache:
    image: redis:7-alpine
    container_name: a-cache
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass V1BHi73KqGRGvHiRkvhxtprUA0F1Hqsi
    volumes: 
      - cache:/data
    networks:
      - net

  migrations:
    build: migrations
    container_name: a-migrations
    command: -connectRetries=20 migrate
    environment:
      FLYWAY_USER: 'postgres'
      FLYWAY_MIXED: 'true'
      FLYWAY_PASSWORD: 'postgres'
      FLYWAY_URL: 'jdbc:postgresql://db:5432/postgres'
    networks:
      - net

volumes:
  db:
    driver: local
  cache:
    driver: local

networks:
  net:
    driver: bridge
